# Copyright (c) 2026 SiOrigin Co. Ltd.
# SPDX-License-Identifier: Apache-2.0

"""Shared filesystem utilities for safe directory traversal.

Provides safe_rglob (list), safe_rglob_iter (generator), safe_is_file,
and walk_files (pruning walk) that handle PermissionError and OSError gracefully.
"""

import os
import subprocess
from collections.abc import Generator, Set as AbstractSet
from fnmatch import fnmatch
from pathlib import Path

from loguru import logger

from core.git_executable import GIT

# Directories that are allowed despite starting with '.'
ALLOWED_HIDDEN_DIRS: frozenset[str] = frozenset({".github", ".gitlab"})

# Metadata directories commonly generated by Python packaging tools.
# These are usually represented as suffixes (e.g. "mypkg.egg-info").
METADATA_DIR_SUFFIXES: frozenset[str] = frozenset({".egg-info", ".dist-info"})


def _git_ls_files(base_path: Path) -> list[str] | None:
    """Try to get tracked file list via git ls-files.

    Returns relative path strings, or None if not a git repo or git fails.
    """
    try:
        result = subprocess.run(
            [GIT, "ls-files"],
            cwd=str(base_path),
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().split("\n")
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass
    return None


def walk_files(
    base_path: Path,
    ignore_dirs: AbstractSet[str],
    gitignore_parser: object | None = None,
    subdirs: AbstractSet[str] | None = None,
) -> list[Path]:
    """Walk directory tree collecting files, pruning ignored/hidden dirs during traversal.

    Uses git ls-files as a fast path when available (reads git index directly,
    no per-file stat calls). Falls back to os.walk with in-place dirnames
    pruning for non-git repos.

    Args:
        base_path: Repository root path.
        ignore_dirs: Set of directory names to skip (e.g. IGNORE_PATTERNS).
        gitignore_parser: Optional GitIgnoreParser instance (must have
            ``should_ignore(path, is_dir=...)`` method). If provided, files
            matching gitignore rules are excluded. Only used in os.walk fallback.
        subdirs: If set, only walk these immediate subdirectories of base_path.

    Returns:
        List of file Paths found.
    """
    # Fast path: use git ls-files (no stat, respects .gitignore natively)
    raw_files = _git_ls_files(base_path)
    if raw_files is not None:
        return _filter_git_files(base_path, raw_files, ignore_dirs, subdirs)

    # Fallback: os.walk with pruning
    return _walk_files_os(base_path, ignore_dirs, gitignore_parser, subdirs)


def _matches_ignored_dir(name: str, ignore_dirs: AbstractSet[str]) -> bool:
    """Return whether a directory name should be pruned."""
    if name in ignore_dirs:
        return True

    for pattern in ignore_dirs:
        if any(ch in pattern for ch in "*?[") and fnmatch(name, pattern):
            return True
        if pattern in METADATA_DIR_SUFFIXES and name.endswith(pattern):
            return True

    return False


def _filter_git_files(
    base_path: Path,
    raw_files: list[str],
    ignore_dirs: AbstractSet[str],
    subdirs: AbstractSet[str] | None,
) -> list[Path]:
    """Filter git ls-files output by ignore_dirs and subdirs (pure string ops, no stat)."""
    files: list[Path] = []
    for rel in raw_files:
        parts = rel.split("/")
        # Check subdirs filter: first path component must be in subdirs
        if subdirs and (not parts or parts[0] not in subdirs):
            continue
        # Check directory parts (all except last which is filename)
        dir_parts = parts[:-1]
        skip = False
        for p in dir_parts:
            if _matches_ignored_dir(p, ignore_dirs):
                skip = True
                break
            if p.startswith(".") and p not in ALLOWED_HIDDEN_DIRS:
                skip = True
                break
        if skip:
            continue
        files.append(base_path / rel)
    logger.info(
        f"git ls-files fast path: {len(files)} files (from {len(raw_files)} tracked, "
        f"filtered {len(raw_files) - len(files)})"
    )
    return files


def _walk_files_os(
    base_path: Path,
    ignore_dirs: AbstractSet[str],
    gitignore_parser: object | None = None,
    subdirs: AbstractSet[str] | None = None,
) -> list[Path]:
    """Fallback: os.walk with in-place dirnames pruning."""
    files: list[Path] = []

    roots: list[Path] = []
    if subdirs:
        for name in subdirs:
            p = base_path / name
            if p.is_dir():
                roots.append(p)
    else:
        roots.append(base_path)

    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root, topdown=True):
            # Prune in-place so os.walk never descends into these
            kept_dirs = []
            for d in dirnames:
                if _matches_ignored_dir(d, ignore_dirs):
                    continue
                if d.startswith(".") and d not in ALLOWED_HIDDEN_DIRS:
                    continue
                # Also prune directories matched by gitignore (e.g. "build/", "dist/")
                if gitignore_parser is not None:
                    try:
                        dir_path = Path(dirpath) / d
                        if gitignore_parser.should_ignore(dir_path, is_dir=True):
                            continue
                    except Exception:
                        pass
                kept_dirs.append(d)
            dirnames[:] = kept_dirs

            dp = Path(dirpath)
            for fname in filenames:
                fp = dp / fname
                if gitignore_parser is not None:
                    try:
                        if gitignore_parser.should_ignore(fp, is_dir=False):
                            continue
                    except Exception:
                        pass
                files.append(fp)

    return files


def safe_rglob(base_path: Path, pattern: str = "*") -> list[Path]:
    """Safely traverse directory tree, skipping files/directories with permission errors.

    Args:
        base_path: The root directory to traverse
        pattern: Glob pattern to match (default: "*")

    Returns:
        List of Path objects that were successfully accessed
    """
    results = []
    try:
        for filepath in base_path.rglob(pattern):
            try:
                filepath.exists()
                results.append(filepath)
            except PermissionError:
                logger.debug(f"Permission denied, skipping: {filepath}")
            except OSError as e:
                logger.debug(f"OS error accessing {filepath}: {e}")
    except PermissionError:
        logger.warning(f"Permission denied accessing directory: {base_path}")
    except OSError as e:
        logger.warning(f"OS error traversing {base_path}: {e}")
    return results


def safe_rglob_iter(base_path: Path, pattern: str = "*") -> Generator[Path, None, None]:
    """Generator version of safe_rglob for memory-efficient traversal.

    Args:
        base_path: The root directory to traverse
        pattern: Glob pattern to match (default: "*")

    Yields:
        Path objects that were successfully accessed
    """
    try:
        for filepath in base_path.rglob(pattern):
            try:
                filepath.exists()
                yield filepath
            except (PermissionError, OSError):
                continue
    except (PermissionError, OSError) as e:
        logger.debug(f"Permission denied accessing directory: {base_path}: {e}")


def safe_is_file(path: Path) -> bool:
    """Safely check if path is a file, returning False on permission errors.

    Args:
        path: Path to check

    Returns:
        True if path is a file and accessible, False otherwise
    """
    try:
        return path.is_file()
    except (PermissionError, OSError):
        return False
